### ISSUE TITLE
7-docs/cli error - Unexpected token A in JSON at position 0

### ISSUE THREAD

**Issue by alanor87** [7-docs/7-docs#1]
Getting "Unexpected token A in JSON at position 0" on attempt to create an index in pinecone database.
 A clean created project, 7-docs is installed locally as a dev dependency.
 OpenAI and pinecone api keys set through 
 `npx 7d set ...`
then running 
`npx 7d pinecone-create-index --index my-index --environment us-east4-gcp`
 - and it gives me "Unexpected token A in JSON at position 0" in console.

**Comment by alanor87** [comment]
Figured it out - perhaps a good idea to mention that in docs) The Pinecone api key is bounded to a certain environment - and in my case it was other than the on mentioned in manual - not us-east4-gcp. So putting the one that is stated on the dashboard of my profile on pinecone solved the issue.

**Comment by webpro** [comment]
Thanks for reporting this! Updated docs and improved some error handling in v0.1.5
