### ISSUE TITLE
Missing PINECONE_URL environment variable

### ISSUE THREAD

**Issue by EugeneMartianov** [7-docs/7-docs#2]
Getting this error when trying to 
`npx 7d ingest` ...
 found the reason - env.ts file - 
`export const OPENAI_API_KEY = process.env.OPENAI_API_KEY ?? get('env', 'OPENAI_API_KEY');
export const PINECONE_URL = process.env.PINECONE_URL;
export const PINECONE_API_KEY = process.env.PINECONE_API_KEY ?? get('env', 'PINECONE_API_KEY');
export const SUPABASE_URL = process.env.SUPABASE_URL ?? get('env', 'SUPABASE_URL');
export const SUPABASE_API_KEY = process.env.SUPABASE_API_KEY ?? get('env', 'SUPABASE_API_KEY');
export const GITHUB_TOKEN = process.env.GITHUB_TOKEN ?? get('env', 'GITHUB_TOKEN');`

As I understand - PINECONE_URL should be obtained the same way, as all others - through the env() call.
 Sorry for my audacity with this - but really like this project, and would like to help it to improve)

**Comment by webpro** [comment]
Thanks for reporting this! Should be fixed now in v0.1.5
